version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3.11.2-management-alpine"
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      AMQP_URL: "amqp://rabbit?connection_attempts=5&retry_delay=5"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - rabbit

networks:
  rabbit:
